/* NINJA Basic model
 * 
 * Generated by SAMDL
 * 
 * Description: Egg Carrier Outside 1 Death Zone 0.sa1mdl
 * 
 */
#include "pch.h"

NJS_MATERIAL matlist_00CF3518[] = {
	{ { 0x60FF0000 }, { 0xFFFFFFFF }, 6, 0, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_IGNORE_LIGHT | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00CF352C[] = {
	4, 3, 2, 1, 0
};

NJS_MESHSET meshlist_00CF3538[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_00CF352C, NULL, NULL, NULL, NULL }
};

NJS_VECTOR vertex_00CF3554[] = {
	{ -2000, 388.88055f, -2000.4608f },
	{ -2000, 388.88055f, 1855.3198f },
	{ 2000, 388.88055f, -2000.4608f },
	{ 2000, 388.88055f, 1855.3198f }
};

NJS_VECTOR normal_00CF3584[] = {
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 }
};

NJS_MODEL attach_00CF35B4 = { vertex_00CF3554, normal_00CF3584, LengthOfArray<Sint32>(vertex_00CF3554), meshlist_00CF3538, matlist_00CF3518, LengthOfArray<Uint16>(meshlist_00CF3538), LengthOfArray<Uint16>(matlist_00CF3518), { 0, 288.88055f, 154.4295f }, 1847.0051f };

NJS_OBJECT object_00CF35E0 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_00CF35B4, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };

PL_KILLCOLLI Death_City[] = {
	{ CharacterFlags_Sonic | CharacterFlags_Gamma | CharacterFlags_Knuckles | CharacterFlags_Big | CharacterFlags_Amy | CharacterFlags_Tails, &object_00CF35E0  },
	{ 0 }
};