/* NINJA Basic+ (with Sonic Adventure DX PC additions) model
 * 
 * Generated by SAMDL
 * 
 */
#include "pch.h"
NJS_MATERIAL matlist_00000094[] = {
	{ { 0x60FF0000 }, { 0xFFFFFFFF }, 6, 0, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_IGNORE_LIGHT | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_8DD9AFCC353E9B9A809[] = {
	4, 0, 1, 3, 2
};

NJS_MESHSET_SADX meshlist_0000007C[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_8DD9AFCC353E9B9A809, NULL, NULL, NULL, NULL, NULL }
};

NJS_VECTOR vertex_00000010[] = {
	{ -10519.1455f, -143.66486f, 7540.924f },
	{ 4539.0957f, -143.66486f, 7576.6133f },
	{ 4396.3633f, -110.89923f, -10981.721f },
	{ -10412.097f, -110.89923f, -10910.342f }
};

NJS_VECTOR normal_00000040[] = {
	{ -0.000042073384f, 0.9999984f, 0.0017757657f },
	{ 0.0000012715939f, 0.9999984f, 0.0017713343f },
	{ 0.000008510687f, 0.9999985f, 0.0017654797f },
	{ 0.000002994889f, 0.9999984f, 0.0017699406f }
};

NJS_MODEL_SADX attach_027BAC5C = { vertex_00000010, normal_00000040, LengthOfArray<Sint32>(vertex_00000010), meshlist_0000007C, matlist_00000094, LengthOfArray<Uint16>(meshlist_0000007C), LengthOfArray<Uint16>(matlist_00000094), { -2990.025f, -127.28204f, -1702.5537f }, 11949.513f, NULL };

NJS_OBJECT object_027BAC88 = { NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_027BAC5C, 0, 0, 0, 0, 0, 0, 5, 1, 5, NULL, NULL };


PL_KILLCOLLI Castlee1_deathzones[] = {
	{ CharacterFlags_Sonic | CharacterFlags_Gamma | CharacterFlags_Knuckles | CharacterFlags_Big | CharacterFlags_Amy | CharacterFlags_Tails, &object_027BAC88 },
	{ 0 }
};