/* NINJA Basic+ (with Sonic Adventure DX PC additions) model
 * 
 * Generated by SAMDL
 * 
 * Description: Mystic Ruins 1 Death Zone 0.sa1mdl
 * 
 */

#include "pch.h"
NJS_MATERIAL matlist_00D03898[] = {
	{ { 0x60FF0000 }, { 0xFFFFFFFF }, 6, 0, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_IGNORE_LIGHT | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00D038AC[] = {
	4, 2, 0, 3, 1
};

NJS_MESHSET_SADX meshlist_00D038B8[] = {
	{ NJD_MESHSET_TRIMESH | 0, 1, poly_00D038AC, NULL, NULL, NULL, NULL, NULL }
};

NJS_VECTOR vertex_00D038D4[] = {
	{ -1049.902f, -432.07904f, -936.98267f },
	{ -1109.8037f, -432.07904f, 2653.1135f },
	{ 3123.237f, -432.07904f, -1035.8491f },
	{ 3163.3196f, -432.07904f, 2862.6619f }
};

NJS_VECTOR normal_00D03904[] = {
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 }
};

NJS_MODEL_SADX attach_00D03934 = { vertex_00D038D4, normal_00D03904, LengthOfArray<Sint32>(vertex_00D038D4), meshlist_00D038B8, matlist_00D03898, LengthOfArray<Uint16>(meshlist_00D038B8), LengthOfArray<Uint16>(matlist_00D03898), { 1026.7579f, -432.07904f, 913.4064f }, 2892.143f, NULL };

NJS_OBJECT object_00D03960 = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_BREAK, &attach_00D03934, 0, 7, 0, 0, 0, 0, 3, 3, 3, NULL, NULL };
PL_KILLCOLLI Forest_deathzones[] = {



	{ CharacterFlags_Sonic | CharacterFlags_Gamma | CharacterFlags_Knuckles | CharacterFlags_Big | CharacterFlags_Amy | CharacterFlags_Tails, &object_00D03960 },
	{ 0 }
};