#pragma once
void SETVIEWDATA_CastleTown();
void CastleTown_Init();
PL_KILLCOLLI* Castle_deathzones[];
void DEATHZONES_CastleTown();
void STARTPOSITIONS_CastleTown();
void newtitlecard();
void initForestmusic();
void FOREST_Init();
Void LANDTABLE_CastleTown();