#pragma once
#include "pch.h"
void Load_NPC_SONICMAN();
extern NJS_TEXLIST TEXLIST_NPC_SONICMAN;
extern NJS_TEXLIST TEXLIST_NPC_SOLDIER;
extern NJS_TEXLIST TEXLIST_NPC_PRIEST;
extern NJS_TEXLIST TEXLIST_NPC_WOMAN1;
void NPC_SONICMAN_Event(task* tp);
AnimationFile* LoadAnim(const char* name);
void NPC_SOLDIER_Event(task* tp);
void Load_NPC_SOLDIER();
void Load_NPC_Priest();
void NPC_SOLDIER2_Event(task* tp);
void NPC_SOLDIER3_Event(task* tp);
void NPC_Woman1_Event(task* tp);
void NPC_Woman2_Event(task* tp);
void NPC_SOLDIER4_Event(task* tp);
void NPC_SOLDIER5_Event(task* tp);
void NPC_Priest2_Event(task* tp);
void NPC_Priest_Event(task* tp);
void NPC_Priest2_Event(task* tp);
void NPC_Priest3_Event(task* tp);
AnimationFile* LoadAnim(const char* name);
extern int x;
void Load_NPC_Woman1();
void NPC_Priest4_Event(task* tp);
void NPC_Priest5_Event(task* tp);
void NPC_Priest6_Event(task* tp);
void NPC_SOLDIER6_Event(task* tp);
void NPC_SOLDIER7_Event(task* tp);
void NPC_SOLDIER8_Event(task* tp);
void NPC_Woman3_Event(task* tp);
void NPC_WomanCity1_Event(task* tp);
void NPC_WomanCity2_Event(task* tp);
void NPC_PriestCity1_Event(task* tp);
void NPC_PriestCity2_Event(task* tp);
void NPC_CITYSOLDIER_Event(task* tp);
