/* NINJA Basic+ (with Sonic Adventure DX PC additions) model
 * 
 * Generated by SAMDL
 * 
 * Description: Emerald Coast 1 Death Zone 0.sa1mdl
 * 
 */
#include "pch.h"

NJS_MATERIAL matlist_00C2F4D0[] = {
	{ { 0x60FF0000 }, { 0xFFFFFFFF }, 6, 0, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_IGNORE_LIGHT | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_00C2F4E4[] = {
	0, 1, 3, 2
};

NJS_MESHSET_SADX meshlist_00C2F4EC[] = {
	{ NJD_MESHSET_4 | 0, 1, poly_00C2F4E4, NULL, NULL, NULL, NULL, NULL }
};

NJS_VECTOR vertex_00C2F508[] = {
	{ -2849, 0, -1703 },
	{ -2878, 0, 3944 },
	{ 7800, 0, 3934 },
	{ 7776, 0, -1718 }
};

NJS_VECTOR normal_00C2F538[] = {
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 },
	{ 0, 1, 0 }
};

NJS_MODEL_SADX attach_00C2F568 = { vertex_00C2F508, normal_00C2F538, LengthOfArray<Sint32>(vertex_00C2F508), meshlist_00C2F4EC, matlist_00C2F4D0, LengthOfArray<Uint16>(meshlist_00C2F4EC), LengthOfArray<Uint16>(matlist_00C2F4D0), { 2461, 0, 1113 }, 6043.135f, NULL };

NJS_OBJECT object_00C2F594 = { NJD_EVAL_UNIT_ANG | NJD_EVAL_BREAK, &attach_00C2F568, 0, -10.018234f, 0, 0, 0, 0, 1, 1, 2.990001f, NULL, NULL };

PL_KILLCOLLI Wave_kill[] = {
	{ CharacterFlags_Sonic | CharacterFlags_Gamma | CharacterFlags_Knuckles  | CharacterFlags_Amy | CharacterFlags_Tails, &object_00C2F594  },
	{ 0 }
};